export enum ServiceCategory {
  SECURITAS = 'SECURITAS',

  SHUTTLESERVICE = 'SHUTTLESERVICE',

  SANITARY = 'SANITARY',

  CLEANINGSERVICE = 'CLEANINGSERVICE',

  PLUMBER = 'PLUMBER',

  DISCJOKEY = 'DISCJOKEY',

  BAND = 'BAND',

  ELECTRONICSTECHNICIAN = 'ELECTRONICSTECHNICIAN',

  COMPUTERSCIENTIST = 'COMPUTERSCIENTIST',

  MISCELLANEOUS = 'MISCELLANEOUS',
}
