# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  #createyourevent-app-dev:
    #image: createyourevent
    #user: "${UID}:${GID}"
    #environment:
      #- _JAVA_OPTIONS=-Xmx512m -Xms256m
      #- SPRING_PROFILES_ACTIVE=prod,api-docs
      #- MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      ## - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://ceo:$${jhipster.registry.password}@34.72.45.31:8761/eureka
      ## - SPRING_CLOUD_CONFIG_URI=http://ceo:$${jhipster.registry.password}@34.72.45.31:8761/config
      #- EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://ceo:ihMMuka8243Schaffhausen!@createyourevent.org:18761/eureka/
      #- SPRING_CLOUD_CONFIG_URI=http://ceo:ihMMuka8243Schaffhausen!@createyourevent.org:18761/config
      #- SPRING_DATASOURCE_URL=jdbc:mysql://createyourevent-mysql-dev:13306/createyourevent?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      #- SPRING_LIQUIBASE_URL=jdbc:mysql://createyourevent-mysql-dev:13306/createyourevent?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      #- SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://www.createyourevent.org:19080/auth/realms/jhipster
      #- SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      #- SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      #- JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    #ports:
      #- 18080:8080
  createyourevent-mysql-dev:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ihMMuka8243
      MYSQL_DATABASE: createyourevent
      MYSQL_USER: createyourideas
      MYSQL_PASSWORD: ihMMuka8243
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 13306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  heartfull-mind-registry-dev:
    image: jhipster/jhipster-registry:v6.7.1
    # image: heartfullmind/registry:latestdoc
    volumes:
      - ./central-server-config:/central-config
    # When run with the "dev" Spring profile, the JHipster Registry will
    # read the config from the local filesystem (central-server-config directory)
    # When run with the "prod" Spring profile, it will read the configuration from a Git repository
    # See https://www.jhipster.tech/jhipster-registry/#spring-cloud-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs ,oauth2
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-server-config/localhost-config/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
      # For keycloak to work, you need to add '127.0.0.1 keycloak' to your hosts file
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://keycloak-dev.createyourevent.org/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=jhipster-registry
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=jhipster-registry
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 18761:8761
  keycloak-dev:
    image: jboss/keycloak:12.0.4
    user: "${UID}:${GID}"
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
      - ./keycloak-postgresql-vol:/opt/jboss/keycloak/standalone/data
      - ./keycloak-themes-folder:/opt/jboss/keycloak/themes/createyourevent
    environment:
      #- KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=ihMMuka8243Schaffhausen!
      - DB_VENDOR=h2
      - PROXY_ADDRESS_FORWARDING=true
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 10080:9080
      - 10443:9443
      - 11990:10990
