# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    oauth2:
      audience:
        - account
        - api://default

eureka:
  client:
    service-url:
      defaultZone: https://registry.createyourevent.org/eureka/
